#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Finder\Finder;


require 'vendor/autoload.php';

$app = new Application('Ashiba', '1.0');

$commands = new Finder();
$commands->files()->in(__DIR__ .'/src/commands');

foreach($commands as $command )
{
    $commandClass = 'Ashiba\Commands\\'. $command->getFilenameWithoutExtension();
    $app->add(new $commandClass() );
}

$app->run();